# Site settings
author: TJ Whipple
title: Exploring Data Science
header-img: img/home-bg.png
email: mrtjwhipple@gmail.com
copyright_name: TJ Whipple
description: > # this means to ignore newlines until "baseurl:"
  A Junior Data Scientist Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  twhipple

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
